inherit_from: .rubocop_todo.yml

Style/FileName:
  Enabled: true
  Exclude:
    - 'lib/dor/migrations/identifiable/assert_adminPolicy.rb'
    - 'lib/dor-services.rb'

# rspec expect{...} is conventional
Style/SpaceBeforeBlockBraces:
  Exclude:
    - 'spec/**/*_spec.rb'

Style/EmptyLineBetweenDefs:
  AllowAdjacentOneLineDefs: true
  Exclude:
    - lib/dor/models/editable.rb
    - lib/dor/models/governable.rb

# Configuration parameters: AllowURI, URISchemes.
Metrics/LineLength:
  Max: 200
