inherit_from: .rubocop_todo.yml
require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.3

Naming/FileName:
  Exclude:
    - 'lib/dor-services.rb'
    - 'spec/dor/releaseable_no_VCR_spec.rb'

Metrics/BlockLength:
  Max: 38
  ExcludedMethods:
    - set_terminology
    - autoload_under
  Exclude:
    - spec/**/*_spec.rb

# Configuration parameters: AllowHeredoc, AllowURI, URISchemes, IgnoreCopDirectives, IgnoredPatterns.
# URISchemes: http, https
Metrics/LineLength:
  Max: 200
  IgnoredPatterns: ['\A#'] # ignore comments

Style/SymbolProc:
  Exclude:
    # causes "Can't create Binding from C level Proc" https://github.com/rubocop-hq/rubocop/issues/6540
    - lib/dor/datastreams/events_ds.rb
