inherit_from: .rubocop_todo.yml

Style/FileName:
  Enabled: true
  Exclude:
    - 'lib/dor/migrations/identifiable/assert_adminPolicy.rb'
    - 'lib/dor-services.rb'

# Configuration parameters: AllowURI, URISchemes.
Metrics/LineLength:
  Max: 200
