inherit_from: .rubocop_todo.yml

Style/FileName:
  Enabled: true
  Exclude:
    - 'lib/dor/migrations/identifiable/assert_adminPolicy.rb'
    - 'lib/dor-services.rb'
    - 'spec/dor/releaseable_no_VCR_spec.rb'

# rspec expect{...} is conventional
Style/SpaceBeforeBlockBraces:
  Exclude:
    - 'spec/**/*_spec.rb'

Style/EmptyLineBetweenDefs:
  AllowAdjacentOneLineDefs: true
  Exclude:
    - lib/dor/models/editable.rb
    - lib/dor/models/governable.rb

Metrics/LineLength:
  Max: 200
  Exclude:
    # rights statement is a single string
    - spec/dor/editable_spec.rb

# test is specifically written this way
Lint/LiteralInCondition:
  Exclude:
    - 'spec/dor/upgradable_spec.rb'
