inherit_from: .rubocop_todo.yml

Naming/FileName:
  Enabled: true
  Exclude:
    - 'lib/dor/migrations/identifiable/assert_adminPolicy.rb'
    - 'lib/dor-services.rb'
    - 'spec/dor/releaseable_no_VCR_spec.rb'

# rspec expect{...} is conventional
Layout/SpaceBeforeBlockBraces:
  Exclude:
    - 'spec/**/*_spec.rb'

Layout/EmptyLineBetweenDefs:
  AllowAdjacentOneLineDefs: true
  Exclude:
    - lib/dor/models/editable.rb
    - lib/dor/models/governable.rb


# Configuration parameters: AllowHeredoc, AllowURI, URISchemes, IgnoreCopDirectives, IgnoredPatterns.
# URISchemes: http, https
Metrics/LineLength:
  Max: 200
  IgnoredPatterns: ['\A#'] # ignore comments
  Exclude:
    # rights statement is a single string
    - spec/models/concerns/editable_spec.rb
    - spec/indexers/editable_indexer_spec.rb
