language: ruby
# caches gems between builds
cache: bundler
sudo: false
notifications:
  email: false

rvm:
  - 2.3.5
  - 2.4.2

env:
  - 'RAILS_VERSION="~> 4.2"'
  - 'RAILS_VERSION="~> 5.0"'
  - 'RAILS_VERSION="~> 5.1"'

matrix:
  include:
    - env: # pre-assembly
        - 'AF_VERSION="~> 6.0"'
        - 'RAILS_VERSION="~> 4.2.5.2"'
      rvm: 2.2.8
    - env:
        - 'AF_VERSION="~> 6.0"'
        - 'RAILS_VERSION="~> 4.2"'
      rvm: 2.3.5
    - env:
        - 'AF_VERSION="~> 7.0"'
        - 'RAILS_VERSION="~> 4.2"'
      rvm: 2.3.5
    - env:
        - 'AF_VERSION="~> 8.0"'
        - 'RAILS_VERSION="~> 4.2"'
      rvm: 2.3.5
