---
:cleanup:
  :local_workspace_root: /dor/workspace
  :local_assembly_root: /dor/assembly
  :local_export_home: /dor/export
:ssl:
  :cert_file:
  :key_file:
  :key_pass: ""
:fedora:
  :url:
  :safeurl:
:stomp:
  :host:
  :user: ""
  :password: ""
  :port: 61613
  :client_id: 'dor-services'
:solrizer:
  :url:
  :opts: {}
:gsearch:
  :rest_url:
  :url:
:metadata:
  :catalog:
    :url:
  :exist:
    :url:
:sdr:
  :local_workspace_root: /dor/workspace
  :local_export_home: /dor/export
  :datastreams:
    :rightsMetadata: optional
    :descMetadata: required
    :sourceMetadata: optional
    :identityMetadata: required
    :provenanceMetadata: required
    :relationshipMetadata: required
    :technicalMetadata: required
    :contentMetadata: required
  :rest_url: ""
:stacks:
  :local_workspace_root: /dor
  :storage_root: /stacks
  :document_cache_storage_root:
  :host:
  :user:
  :document_cache_host:
  :document_cache_user:
  :local_stacks_root: /stacks
  :local_document_cache_root: /purl
:suri:
  :pass:
  :id_namespace: druid
  :url:
  :user:
  :mint_ids: false
:workflow:
  :url:
  :timeout: 60
:dor_services:
  :url:
