---
:cleanup:
  :local_workspace_root: /dor/workspace
  :local_assembly_root: /dor/assembly
  :local_export_home: /dor/export
:ssl:
  :cert_file:
  :key_file:
  :key_pass: ""
:fedora:
  :url:
:solr:
  :url:
  :opts: {}
:stacks:
  :local_workspace_root: /dor
  :document_cache_host:
  :local_stacks_root: /stacks
  :local_document_cache_root: /purl/document_cache
:suri:
  :pass:
  :id_namespace: druid
  :url:
  :user:
  :mint_ids: false
:workflow:
  :url:
  :timeout: 60
  :logfile: workflow_service.log
  :shift_age: weekly
