---
ssl:
  cert_file:
  key_file:
  key_pass: ""
fedora:
  url:
solr:
  url:
stacks:
  local_workspace_root: /dor
  local_stacks_root: /stacks
  local_document_cache_root: /purl/document_cache
suri:
  pass:
  id_namespace: druid
  url:
  user:
  mint_ids: false
