---
:cleanup:
  :local_workspace_root: /dor/workspace
  :local_assembly_root: /dor/assembly
  :local_export_home: /dor/export
:ssl:
  :cert_file:
  :key_file:
  :key_pass: ""
:fedora:
  :url:
:solr:
  :url:
  :opts: {}
:metadata:
  :catalog:
    :url:
    :user:
    :pass:
:sdr:
  :local_workspace_root: /dor/workspace
  :local_export_home: /dor/export
  :datastreams:
    :rightsMetadata: optional
    :descMetadata: required
    :sourceMetadata: optional
    :identityMetadata: required
    :provenanceMetadata: required
    :relationshipMetadata: required
    :technicalMetadata: required
    :contentMetadata: required
  :rest_url: ""
:stacks:
  :local_workspace_root: /dor
  :host:
  :user:
  :document_cache_host:
  :document_cache_user:
  :local_stacks_root: /stacks
  :local_document_cache_root: /purl/document_cache
  :url:
  :iiif_profile: 'http://iiif.io/api/image/2/level1.json'
:suri:
  :pass:
  :id_namespace: druid
  :url:
  :user:
  :mint_ids: false
:workflow:
  :url:
  :timeout: 60
  :logfile: workflow_service.log
  :shift_age: weekly
:dor_services:
  :url:
:dor_indexing_app:
  :url:
:indexing_svc:
  :log: 'log/indexing_svc.log'
  :log_date_format_str: '%Y-%m-%d %H:%M:%S.%L'
  :log_rotation_interval: 'daily'
:goobi:
  :url:
  :dpg_workflow_name: 'goobiWF'
  :default_goobi_workflow_name: 'Example_Workflow'
  :max_tries: 3
  :max_sleep_seconds: 20
  :base_sleep_seconds: 2
